# ~/projects/rw_deploy/infra-compose.yml
version: '3.8'

x-podman-defaults: &podman-defaults
  security_opt:
    - no-new-privileges:true
    - label=disable
  cap_drop:
    - ALL
  restart: "always"

services:
  nginx:
    image: nginx:alpine
    container_name: rockwillow-nginx
    user: "101:101"  # nginx user in alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ${HOME}/projects/rw_deploy/nginx/conf.d:/etc/nginx/conf.d:z,ro
      - ${HOME}/projects/rw_deploy/nginx/ssl:/etc/nginx/ssl:z,ro
      - ${HOME}/projects/rw_deploy/nginx/html:/usr/share/nginx/html:z,ro
      - ${HOME}/projects/rw_deploy/nginx/logrotate.conf:/etc/logrotate.d/nginx-custom:ro
      - ${HOME}/data/nginx/logs:/var/log/nginx:z
      - ${HOME}/data/nginx/tmp:/var/cache/nginx:z
      - ${HOME}/data/nginx/run:/var/run:z
    networks:
      - rockwillow-network
    <<: *podman-defaults
    healthcheck:
      test: ["CMD-SHELL", "nginx -t || exit 1"]
      interval: 30s
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE

  mariadb:
    image: mariadb:11
    container_name: rockwillow-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-ChangeMe123!}
      MARIADB_DATABASE: ${DB_NAME:-rockwillow_budget}
      MARIADB_USER: ${DB_USER:-budget_user}
      MARIADB_PASSWORD: ${DB_PASSWORD:-ChangeMe456!}
      TZ: ${TZ:-America/New_York}
    volumes:
      - ${HOME}/data/mariadb/data:/var/lib/mysql:Z
      - ${HOME}/data/mariadb/logs/:/var/log/mysql:z
      - ${HOME}/data/backups:/backups:z
      - ${HOME}/projects/rw_deploy/db/init.sql:/docker-entrypoint-initdb.d/init.sql:z,ro
    ports:
      - "3307:3306"
    networks:
      - rockwillow-network
    <<: *podman-defaults
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 30s
      retries: 5
      start_period: 60s
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    user: "999:999"  # mysql user in MariaDB container
    tmpfs:
      - /tmp:size=100M,mode=1777

networks:
  rockwillow-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16